print("Programmer: John Carlo M. Garabiles")
print("Date Created: July 6, 2023")
print("Description of the Program: This is Personal Information")
print("First Name: John Carlo")
print("Middle Name: Mateo")
print("Last Name: Garabiles")
print("Course: BSIT")
print("Year: 3rd year")
print("Age: 20")
print("Gender: Male")
print("Civil Status: Signle")
print("Nationality: Filipino")
print("Motto: Pag pagod ka magpahinga ka.")

print("School: PHINMA Araullo University")
print("College: CITE")